site_name: Lumos's Docs
site_description: A personal documentation portal
site_author: Lumos

theme:
  name: material
  
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - def_list

nav:
  - Homepage: index.md

  - Technical Writing: 
      - "Technical Writing/Steps to Update GitHub.md"
      - "Technical Writing/Tips to Write Markdown Docs.md"

  - Translation:
      - "Translation/Matecat.md"
      - "Translation/Localization Notes.md"
      - "Translation/Overview.md"
      
  - Tools: "Tools/Tools.md"
  
  
      
